compute_environment: LOCAL_MACHINE
torchdynamo: "none"
debug: true
deepspeed_config:
  deepspeed_config_file: /gscratch/stf/lbc800/mistral-KD/deepspeedconfig.json
distributed_type: DEEPSPEED
downcast_bf16: "no"
dynamo_config:
  dynamo_backend: INDUCTOR
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 3
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
